#@data/values
---
#! your system domain, e.g., "system.cf.example.com"
system_domain:
#! list of app domains, e.g., ["apps.cf.example.com"]
app_domains: []

#! password for admin user in plain text
cf_admin_password:

#! reserved static ip for LoadBalancer
load_balancer:
  enable: true
  static_ip: ""

system_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.system.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the system certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the system certifcate
  ca: ""

workloads_certificate:
  #! Base64-encoded certificate for the wildcard
  #! subdomain of the system domain (e.g., CN=*.apps.cf.example.com)
  crt: ""
  #! Base64-encoded private key for the workloads certificate
  key: ""
  #! Base64-encoded CA certificate used to sign the workloads certifcate
  ca: ""

#! When true, automatically upgrades incoming HTTP connections to HTTPS
gateway:
  https_only: true

capi:
  database:
    #! or mysql2, as needed
    adapter: postgres
    encryption_key: ""
    host: ""
    port: 5432
    user: cloud_controller
    #! DB user password in plain text
    password: ""
    name: cloud_controller
    #! Plain text ca certificate if tls should be used
    ca_cert: ""
  log_level: info

uaa:
  database:
    #! or mysql2, as needed
    adapter: postgresql
    host: ""
    port: 5432
    user: uaa
    #! DB user password in plain text
    password: ""
    name: uaa
    #! Plain text ca certificate for tls
    ca_cert: ""

app_registry:
  hostname: ""
  repository_prefix: ""
  username: ""
  password: ""

add_metrics_server_components: false
enable_automount_service_account_token: false
enable_load_balancer: true
metrics_server_prefer_internal_kubelet_address: false
remove_resource_requirements: false
use_external_dns_for_wildcard: false
use_first_party_jwt_tokens: false

#! configuration for the CF blobstore
blobstore:
  endpoint: "http://cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000"
  region: "''"
  access_key_id: "admin"
  secret_access_key: ""
  package_directory_key: "cc-packages"
  droplet_directory_key: "cc-droplets"
  resource_directory_key: "cc-resources"
  buildpack_directory_key: "cc-buildpacks"
  aws_signature_version: "2"
