---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs: []

params: {}

outputs: []

run:
  path: cf-for-k8s-ci/ci/tasks/fail/task.sh
