---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci

outputs:
  - name: tf-vars

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:
  DATABASE_PASSWORD:

run:
  path: /bin/bash
  args:
  - -ec
  - |
    cat <<EOT > tf-vars/input.tfvars
    region = "$AWS_REGION"
    aws_access_key_id = "$AWS_ACCESS_KEY_ID"
    aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY"
    database_password = "$DATABASE_PASSWORD"
    EOT
