#@ load("/values.star", "data")
#@ load("@ytt:overlay", "overlay")

#! this gateway is used to expose CF services in the cluster, externally
#@ load("gateway.lib.yaml", "gateway")

#@ def external_routing():
--- #@ gateway(data.values.system_domain, data.values.app_domains, data.values.system_namespace, data.values.workloads_namespace, data.values.gateway.https_only)

#! this secret contains the certificate/key combo used for the external system domain
---
apiVersion: v1
kind: Secret
metadata:
  name: cf-system-cert
  namespace: istio-system
  annotations:
    kapp.k14s.io/change-rule.istio-ingressgateway: "upsert before upserting istio.io/ingressgateway"
stringData:
  tls.key: #@ data.values.system_certificate.key
  tls.crt: #@ data.values.system_certificate.crt
type: kubernetes.io/tls

---
apiVersion: v1
kind: Secret
metadata:
  name: cf-workloads-cert
  namespace: istio-system
  annotations:
    kapp.k14s.io/change-rule.istio-ingressgateway: "upsert before upserting istio.io/ingressgateway"
stringData:
  tls.key: #@ data.values.workloads_certificate.key
  tls.crt: #@ data.values.workloads_certificate.crt
type: kubernetes.io/tls

#! the following overlay ensures the above Secret is created before the ingressgateway since we're not using SDS
#! ingressgateway can be either a Deployment or a DaemonSet
#@ deployment = overlay.subset({"kind": "Deployment", "metadata":{"name":"istio-ingressgateway"}})
#@ daemonset = overlay.subset({"kind": "DaemonSet", "metadata":{"name":"istio-ingressgateway"}})
#@ match_ingress_gateway=overlay.or_op(deployment, daemonset)
#@overlay/match by=match_ingress_gateway
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group: istio.io/ingressgateway

#! This will set overlay a static IP for the istio load balancer.
#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name": "istio-ingressgateway"}})
---
#@ if data.values.load_balancer.static_ip:
spec:
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.load_balancer.static_ip
#@ end
#@ end
