---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci
  - name: cf-for-k8s
  - name: runtime-ci
    optional: true
  - name: pool-lock
    optional: true
  - name: tf-vars
    optional: true
  - name: terraform
    optional: true
  - name: env-metadata
    optional: true
  - name: db-metadata
    optional: true
  - name: blobstore-metadata
    optional: true

params:
  GCP_SERVICE_ACCOUNT_JSON:
  GCP_PROJECT_NAME:
  GCP_PROJECT_ZONE:
  DOMAIN:
  USE_EXTERNAL_APP_REGISTRY: false
  APP_REGISTRY_HOSTNAME:
  APP_REGISTRY_REPOSITORY_PREFIX:
  APP_REGISTRY_USERNAME:
  APP_REGISTRY_PASSWORD:
  UPGRADE: false
  UPTIMER: false
  UPTIMER_FAIL_ON_DOWNTIME: false
  EMIT_UPTIMER_METRICS_TO_WAVEFRONT: false
  WAVEFRONT_API_KEY:
  WAVEFRONT_API_ENDPOINT:
  USE_EXTERNAL_DB: false
  USE_EXTERNAL_BLOBSTORE: false

outputs:
  - name: env-metadata

run:
  path: cf-for-k8s-ci/ci/tasks/install-cf-on-gke/task.sh
