#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: log-cache-ca
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.log_cache_ca.crt
  tls.key: #@ data.values.log_cache_ca.key

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: log-cache
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.log_cache.crt
  tls.key: #@ data.values.log_cache.key

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: log-cache-metrics
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.log_cache_metrics.crt
  tls.key: #@ data.values.log_cache_metrics.key

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: log-cache-gateway
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.log_cache_gateway.crt
  tls.key: #@ data.values.log_cache_gateway.key

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: log-cache-syslog
  namespace: #@ data.values.system_namespace
data:
  tls.crt: #@ data.values.log_cache_syslog.crt
  tls.key: #@ data.values.log_cache_syslog.key