---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: pool-repo
- name: cf-for-k8s-develop-ci

outputs:
- name: new-lock

run:
  path: cf-for-k8s-develop-ci/ci/tasks/generate-random-name/task.sh
