---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci
  - name: tf-vars
    optional: true
  - name: terraform-s3
    optional: true

outputs:
  - name: blobstore-metadata

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_REGION:

run:
  path: cf-for-k8s-ci/ci/tasks/create-s3-bucket-data-values-file/task.sh
