#@ load("@ytt:data","data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-deployment-updater
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capi-deployment-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capi-deployment-updater
    spec:
      #@ if/end data.values.imagePullSecrets:
      imagePullSecrets: #@ data.values.imagePullSecrets
      containers:
        - name: capi-deployment-updater
          workingDir: "/cloud_controller_ng"
          command: ["/usr/local/bin/bundle"]
          args: ["exec", "rake", "deployment_updater:start"]
          image: #@ data.values.images.ccng
          imagePullPolicy: Always
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      volumes:
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
