---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-for-k8s-ci

inputs:
- name: cf-for-k8s
- name: cf-for-k8s-ci
- name: env-metadata
- name: terraform

params:
  GCP_KEY: ~
  GCP_PROJECT_NAME: ~

run:
  path: cf-for-k8s-ci/ci/tasks/run-smoke-tests-on-kind/task.sh
