platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking
  - name: version
  - name: cf-for-k8s-ci

outputs:
  - name: release-text

run:
  path: cf-for-k8s-ci/ci/tasks/cf-k8s-networking/generate-github-release.sh
