platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-k8s-networking
  - name: cf-for-k8s-ci
  - name: integration-config
  - name: pool-lock

params:
  CONFIG_KEEP_CLUSTER:
  # - Optional
  # - Set to non empty value to keep changes done on Kubernetes cluster after the test run
  CONFIG_KEEP_CF:
  # - Optional
  # - Set to non empty value to keep changes done on CF after the test run
  FLAKE_ATTEMPTS:
  GCP_PROJECT_NAME:
  GCP_PROJECT_ZONE:
  GCP_SERVICE_ACCOUNT_JSON:
  INTEGRATION_CONFIG_FILE: "config.json"
  # - JSON file with configurations

run:
  path: cf-for-k8s-ci/ci/tasks/cf-k8s-networking/run-networking-acceptance-gke.sh
