platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
- name: cf-for-k8s-ci
- name: cf-for-k8s-develop
- name: image-resource

outputs:
- name: cf-for-k8s-modified

run:
  path: cf-for-k8s-ci/ci/tasks/cf-k8s-networking/update-image-digest-in-cf-for-k8s.sh

params:
  TARGET_FILE: # e.g. config/values.yml
  COMPONENT_NAME: # e.g. routecontroller
  GIT_COMMIT_USERNAME: "relint-ci"
  GIT_COMMIT_EMAIL: "cf-release-integration@pivotal.io"
