#@ load("/values.star", "data")
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: fluentd-allow-plaintext
  namespace: #@ data.values.system_namespace
spec:
  selector:
    matchLabels:
      app: fluentd
  mtls:
    mode: PERMISSIVE
