#@data/values
---
app_domains: []
blobstore:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  buildpack_directory_key: cc-buildpacks
  droplet_directory_key: cc-droplets
  endpoint: http://capi-blobstore-minio.default:9000
  package_directory_key: cc-packages
  aws_signature_version: '2'
  region: ""
  resource_directory_key: cc-resources
  secret_access_key_secret_name:
  fog_aws_storage_options: {}
cc:
  log_level: info
ccdb:
  adapter: postgres
  database: cloud_controller
  host: capi-database-postgresql
  password_secret_name:
  encryption_key_secret_name: capi-database-encryption-key-secret
  port: 5432
  user: cloud_controller
  ca_cert: null
eirini:
  serverCerts:
    secretName: null
imagePullSecrets: null
kpack:
  registry:
    hostname: ""
    password: ""
    repository_prefix: ""
    username: ""
#! TODO: remove metric_proxy certs after PR to cf-for-k8s
metric_proxy:
  ca:
    secret_name: null
  cert:
    secret_name: null
replicaCount: 1
staging_namespace: cf-workloads-staging
system_domain: cf-system.svc.cluster.local
system_namespace: cf-system
uaa:
  clients:
    cf_api_controllers:
      secret_name:
    cf_api_backup_metadata_generator:
      secret_name:
    cloud_controller_username_lookup:
      secret_name:
  serverCerts:
    secretName: null
workloads_namespace: cf-workloads
temporary_disable_v2_staging: true
honeycomb:
  write_key: ""
  dataset: ""
