---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: pool-repo
- name: cf-for-k8s-develop-ci

params:
  POOL_SIZE_BUFFER_TARGET:

run:
  path: cf-for-k8s-develop-ci/ci/tasks/check-pool-size/task.sh
