---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci
  - name: pool-lock
    optional: true
  - name: tf-vars
    optional: true
  - name: terraform
    optional: true

outputs:
  - name: db-metadata

params:
  GCP_SERVICE_ACCOUNT_JSON:
  GCP_PROJECT_NAME:
  GCP_PROJECT_ZONE:

run:
  path: cf-for-k8s-ci/ci/tasks/install-postgres/task.sh
