#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

systemNamespace: cf-system
workloadsNamespace: cf-workloads

cfroutesync:
  image: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:87704f76960a66e5f11a73ad1a853f5e06203d29d00ef4dc3f61ad81feee1898

  ccCA: 'base64_encoded_cloud_controller_ca'
  ccBaseURL: 'https://api.example.com'
  uaaCA: 'base64_encoded_uaa_ca'
  uaaBaseURL: 'https://uaa.example.com'
  clientName: 'uaaClientName'
  clientSecret: 'base64_encoded_uaaClientSecret'

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:717940947ac6b90ccf17a202b5e8eec58388c211dfa26495503471442f5a7202

service:
  externalPort: 80
