#@data/values
---
#! Default values for cf-k8s-networking.
#! This is a YTT-formatted file.

systemNamespace: cf-system
workloadsNamespace: cf-workloads

cfroutesync:
  image: gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:2afc84d57dc89371dccf53302bad0e5dc23dd780fd91577b98c4dc13b62201f4

  ccCA: 'base64_encoded_cloud_controller_ca'
  ccBaseURL: 'https://api.example.com'
  uaaCA: 'base64_encoded_uaa_ca'
  uaaBaseURL: 'https://uaa.example.com'
  clientName: 'uaaClientName'
  clientSecret: 'base64_encoded_uaaClientSecret'

routecontroller:
  image: gcr.io/cf-networking-images/cf-k8s-networking/routecontroller@sha256:a51cb69313f98c658b9f45f97cebd1dbc2d70e84aafde602e5d370c928502bce

service:
  externalPort: 80
