#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-api-controllers
  namespace: #@ data.values.system_namespace
  labels:
    app.kubernetes.io/name: cf-api-controllers
    app.kubernetes.io/instance: cf-api-controllers-0
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cf-api-controllers
  template:
    metadata:
      annotations:
        pre.hook.backup.velero.io/container: backup-metadata-generator
        pre.hook.backup.velero.io/command: '["/cnb/process/generate-metadata"]'
      labels:
        app: cf-api-controllers
        app.kubernetes.io/name: cf-api-controllers
    spec:
      serviceAccountName: cf-api-controllers-service-account
      containers:
      - name: manager
        image: #@ data.values.images.cf_api_controllers
        env:
        - name: UAA_CLIENT_SECRET_FILE
          value: /config/uaa_client_secret/password
        - name: UAA_ENDPOINT
          value: #@ "http://uaa.{}.svc.cluster.local:8080".format(data.values.system_namespace)
        - name: UAA_CLIENT_NAME
          value: cf_api_controllers
        - name: CF_API_HOST
          value: #@ "http://capi.{}.svc.cluster.local".format(data.values.system_namespace)
        - name: WORKLOADS_NAMESPACE
          value: #@ data.values.workloads_namespace
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: uaa-client-secret
            mountPath: /config/uaa_client_secret
      - name: backup-metadata-generator
        image: #@ data.values.images.backup_metadata_generator
        imagePullPolicy: Always
        command: [ "/cnb/process/wait" ]
        env:
        - name: CF_API_HOST
          value: #@ "http://capi.{}.svc.cluster.local".format(data.values.system_namespace)
        - name: CF_CLIENT
          value: cf_api_backup_metadata_generator
        - name: CF_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: password
              name: #@ data.values.uaa.clients.cf_api_backup_metadata_generator.secret_name
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
        - name: uaa-client-secret
          secret:
            secretName: #@ data.values.uaa.clients.cf_api_controllers.secret_name
      terminationGracePeriodSeconds: 10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cf-api-controllers
rules:
- apiGroups: ["kpack.io"]
  resources: ["images", "builds", "builds/status", "images/status"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controllers-binding
subjects:
- kind: ServiceAccount
  namespace: #@ data.values.system_namespace
  name: cf-api-controllers-service-account
roleRef:
  kind: ClusterRole
  name: cf-api-controllers
  apiGroup: rbac.authorization.k8s.io
