#@ load("@ytt:data","data")
#@ load("@ytt:template", "template")
#@ load("secrets.lib.yml","shared_config_volumes", "shared_config_volume_mounts", "ccng_config_mount_path", "ccng_secrets_mount_path")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-api-worker
  namespace: #@ data.values.system_namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cf-api-worker
  template:
    metadata:
      labels:
        app: cf-api-worker
        app.kubernetes.io/name: cf-api-worker
    spec:
      #@ if/end data.values.imagePullSecrets:
      imagePullSecrets: #@ data.values.imagePullSecrets
      containers:
        - name: cf-api-worker
          image: #@ data.values.images.ccng
          imagePullPolicy: Always
          command: [ "/cnb/process/api-worker" ]
          ports:
          - containerPort: 4444
          env:
          - name: CLOUD_CONTROLLER_NG_CONFIG
            value: #@ ccng_config_mount_path
          - name: CLOUD_CONTROLLER_NG_SECRETS
            value: #@ ccng_secrets_mount_path
          - name: INDEX
            value: "1"
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 4444
            periodSeconds: 3
          volumeMounts:
          - #@ template.replace(shared_config_volume_mounts())
          #@ if/end data.values.eirini.serverCerts.secretName:
          - name: eirini-certs
            mountPath: /config/eirini/certs
          #@ if/end data.values.ccdb.ca_cert:
          - name: database-ca-cert
            mountPath: /config/database/certs
        - name: registry-buddy
          image: #@ data.values.images.registry_buddy
          imagePullPolicy: Always
          env:
            - name: REGISTRY_BASE_PATH
              value: #@ data.values.kpack.registry.repository_prefix
            - name: REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cc-package-registry-upload-secret
                  key: username
            - name: REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cc-package-registry-upload-secret
                  key: password
          livenessProbe:
            exec:
              command:
              #! We cannot use a http liveness probe for security concerns. See this ADR for more information:
              #! https://github.com/cloudfoundry/capi-k8s-release/blob/main/decisions/0005-exec-curl-instead-of-http-liveness-probe-registry-buddy.md
              - curl
              - --silent
              - --fail
              - --show-error
              - localhost:8080/healthz
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 15Mi
            limits:
              cpu: 15000m
              memory: 150Mi
      serviceAccountName: cf-api-worker-service-account
      volumes:
      - #@ template.replace(shared_config_volumes())
      #@ if/end data.values.eirini.serverCerts.secretName:
      - name: eirini-certs
        secret:
          secretName: #@ data.values.eirini.serverCerts.secretName
      #@ if/end data.values.ccdb.ca_cert:
      - name: database-ca-cert
        secret:
          secretName: database-ca-cert

