#@data/values
---
images:
  backup_metadata_generator: cloudfoundry/cf-api-backup-metadata-generator@sha256:9049945ede457502ef6ee89bb99bacb3dea798d48eb6b23216274c03a6355bde
  ccng: cloudfoundry/cloud-controller-ng@sha256:681bf3175147d4e358a10c57457e3b8dab317e943f1e7491b8808955dc8fe734
  cf_api_controllers: cloudfoundry/cf-api-controllers@sha256:4f8247163c1e7b72c28f2ff3fafd54847f195c557c064c035166123d001c15af
  cf_autodetect_builder: cloudfoundry/cnb:0.0.94-bionic@sha256:5b03a853e636b78c44e475bbc514e2b7b140cc41cca8ab907e9753431ae8c0b0
  nginx: cloudfoundry/capi-nginx@sha256:04dbaba65a3002f2225735c312788317035afc8971864ce34a91e077a90742c4
  registry_buddy: cloudfoundry/cf-api-package-registry-buddy@sha256:77f631c8cc3b6887ec3bb8e08d283f2954c2f4fac6a72ffb4e8c6c9c7a093c7a
  statsd_exporter: cloudfoundry/statsd_exporter:v0.15.0@sha256:10a64dc4ad0a3e3fe88372f0481dea5c02595c38d168617836a99a649d3ac407
