#@data/values
---
images:
  backup_metadata_generator: cloudfoundry/cf-api-backup-metadata-generator@sha256:9049945ede457502ef6ee89bb99bacb3dea798d48eb6b23216274c03a6355bde
  ccng: cloudfoundry/cloud-controller-ng@sha256:72dfafe2b506332d910e82137234b7a60129901b612a0edacb4d8458145e16d7
  cf_api_controllers: cloudfoundry/cf-api-controllers@sha256:e0bd33b8e91bb59971fc69678a994e3e2b6c1c270b43487f19b6eb54653b7740
  cf_autodetect_builder: cloudfoundry/cnb:0.0.94-bionic@sha256:5b03a853e636b78c44e475bbc514e2b7b140cc41cca8ab907e9753431ae8c0b0
  nginx: cloudfoundry/capi-nginx@sha256:04dbaba65a3002f2225735c312788317035afc8971864ce34a91e077a90742c4
  registry_buddy: cloudfoundry/cf-api-package-registry-buddy@sha256:87a6c4d2ec14d97f8c193a6b8dd2c26926eaa78eb85052997ae55cbb34880ad0
  statsd_exporter: cloudfoundry/statsd_exporter:v0.15.0@sha256:10a64dc4ad0a3e3fe88372f0481dea5c02595c38d168617836a99a649d3ac407
