---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-test-runner

inputs:
- name: cf-for-k8s-latest-release
- name: cf-for-k8s-develop-ci
- name: env-metadata

params:
  APP_NAME:

run:
  path: cf-for-k8s-develop-ci/ci/tasks/push-test-app/task.sh
