---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-test-runner

inputs:
- name: cf-for-k8s-repo
- name: cf-for-k8s-ci
- name: env-metadata

params:
  APP_NAME:
  VERIFY_EXISTING_APP:

run:
  path: cf-for-k8s-ci/ci/tasks/push-test-app/task.sh
