#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routecontroller
  namespace: #@ data.values.systemNamespace
  labels:
    app.kubernetes.io/name: routecontroller
    app.kubernetes.io/component: cf-networking
    app.kubernetes.io/part-of: cloudfoundry
rules:
- apiGroups: ["networking.cloudfoundry.org"]
  resources: ["routes", "routes/status"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: ["projectcontour.io"]
  resources: ["httpproxies"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
