apiVersion: v1
kind: Namespace
metadata:
  name: kpack
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builds.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Image
      type: string
      jsonPath: .status.latestImage
    - name: Succeeded
      type: string
      jsonPath: .status.conditions[?(@.type=="Succeeded")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Image
      type: string
      jsonPath: .status.latestImage
    - name: Succeeded
      type: string
      jsonPath: .status.conditions[?(@.type=="Succeeded")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: Build
    listKind: BuildList
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    - blds
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builders.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: Builder
    listKind: BuilderList
    singular: builder
    plural: builders
    shortNames:
    - bldr
    - bldrs
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  names:
    kind: ClusterBuilder
    listKind: ClusterBuilderList
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
    - clstbldr
    - clstbldrs
    categories:
    - kpack
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstacks.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  names:
    kind: ClusterStack
    listKind: ClusterStackList
    singular: clusterstack
    plural: clusterstacks
    categories:
    - kpack
  scope: Cluster
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterstores.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    subresources:
      status: {}
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    subresources:
      status: {}
  names:
    kind: ClusterStore
    listKind: ClusterStoreList
    singular: clusterstore
    plural: clusterstores
    categories:
    - kpack
  scope: Cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-init@sha256:79cf7c093f8f92e074f94bc16e2183a1b1447691946d074b7766352fc7133e93
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-windows-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-init-windows@sha256:b09db5c6b65a9927353adb423901892818aabea2f358f264026ed0cbce1519c2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebase-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/rebase@sha256:47cae0a6cf696d93defd5028b550a8f54f7fd02301ff8435152f5822c76f7ce0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lifecycle-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/lifecycle@sha256:82cd719d22df7cfa84391ac2e73c683b77b560947790de1af9b320ccdb9eab1c
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/completion@sha256:5af33141badefcc299e4d4b1b8c3017a476d33534ad7274bbe0f38359c303ef5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completion-windows-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/completion-windows@sha256:57f6b0da8a0b4ebe797424735f4a54e77befd7f07c70731b4a2187785137cf6e
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: 0.4.3-rc.3
    spec:
      serviceAccountName: controller
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: controller
        image: gcr.io/cf-build-service-public/kpack/controller@sha256:ef071d94048556fab5a2192d61c0da339f525caccf656a7239fe62340f96b4e4
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BUILD_INIT_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-image
              key: image
        - name: BUILD_INIT_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: build-init-windows-image
              key: image
        - name: REBASE_IMAGE
          valueFrom:
            configMapKeyRef:
              name: rebase-image
              key: image
        - name: COMPLETION_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-image
              key: image
        - name: COMPLETION_WINDOWS_IMAGE
          valueFrom:
            configMapKeyRef:
              name: completion-windows-image
              key: image
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 500Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: kpack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-controller-admin
rules:
- apiGroups:
  - kpack.io
  resources:
  - builds
  - builds/status
  - builds/finalizers
  - images
  - images/status
  - images/finalizers
  - builders
  - builders/status
  - clusterbuilders
  - clusterbuilders/status
  - clusterstores
  - clusterstores/status
  - clusterstacks
  - clusterstacks/status
  - sourceresolvers
  - sourceresolvers/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-admin-binding
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-controller-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-controller-local-config
  namespace: kpack
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-controller-local-config-binding
  namespace: kpack
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: Role
  name: kpack-controller-local-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: images.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: LatestImage
      type: string
      jsonPath: .status.latestImage
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: Image
    listKind: ImageList
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    - img
    - imgs
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: v1
kind: Service
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    role: webhook
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sourceresolvers.kpack.io
spec:
  group: kpack.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kpack-webhook
          namespace: kpack
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
  names:
    kind: SourceResolver
    listKind: SourceResolverList
    singular: sourceresolver
    plural: sourceresolvers
    categories:
    - kpack
  scope: Namespaced
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaults.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  name: defaults.webhook.kpack.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  matchPolicy: Exact
  sideEffects: None
  name: validation.webhook.kpack.io
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: kpack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: 0.4.3-rc.3
    spec:
      serviceAccountName: webhook
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: webhook
        image: gcr.io/cf-build-service-public/kpack/webhook@sha256:789bae040b955952716218342925cc955d531965096001a3653b07b3f62937a5
        ports:
        - name: https-webhook
          containerPort: 8443
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: kpack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-webhook-certs-admin
  namespace: kpack
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - webhook-certs
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-webhook-certs-admin-binding
  namespace: kpack
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: kpack
roleRef:
  kind: Role
  name: kpack-webhook-certs-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-webhook-mutatingwebhookconfiguration-admin
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - kpack
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  resourceNames:
  - defaults.webhook.kpack.io
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - validation.webhook.kpack.io
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - images.kpack.io
  - builds.kpack.io
  - builders.kpack.io
  - sourceresolvers.kpack.io
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-webhook-certs-mutatingwebhookconfiguration-admin-binding
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-webhook-mutatingwebhookconfiguration-admin
  apiGroup: rbac.authorization.k8s.io
